dist: bionic
cache: pip

language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"

install:
  - sudo apt-get install -y ninja-build pybind11-dev libdatrie-dev
  - pip install tox-travis

script: tox
