name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    env:
      OS: ${{ matrix.os }}
      PYTHON: ${{ matrix.python-version }}
      PYTHONIOENCODING: utf-8
      PIP_DOWNLOAD_CACHE: ${{ github.workspace }}/../.pip_download_cache
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, macos-latest, windows-latest]
        python-version: [3.6, 3.7, 3.8, 3.9]

    steps:
    - name: Set git crlf/eol
      run: |
        git config --global core.autocrlf false
        git config --global core.eol lf

    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        submodules: true

    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Set HAVE_LIBDATRIE_PKG var
      if: runner.os == 'Linux'
      shell: bash
      env:
        HAVE_LIBDATRIE_PKG: true
      run: |
        echo "HAVE_LIBDATRIE_PKG is ${HAVE_LIBDATRIE_PKG}"
        echo "HAVE_LIBDATRIE_PKG=${HAVE_LIBDATRIE_PKG}" >> $GITHUB_ENV

    - name: Install deps with apt helper action
      if: runner.os == 'Linux'
      uses: ryankurte/action-apt@v0.2.0
      with:
        # architectures to pass to dpkg --add-architecture
        #architectures: # optional
        packages: pybind11-dev libdatrie-dev

    - name: Install macos deps with brew
      if: runner.os == 'macOS'
      run: |
        brew install pybind11

    - name: Prepare build environment for windows
      if: runner.os == 'Windows'
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x64

    #- name: Install deps with vcpkg
      #if: runner.os == 'Windows'
      #run: |
        #echo $VCPKG_ROOT
        #vcpkg install pybind11:x64-windows
        #vcpkg integrate install

    - name: Add pip requirements
      run: |
        python -m pip install --upgrade pip
        pip install tox tox-gh-actions

    - name: Test via pip develop
      run: |
        tox -e dev

    - name: Build dist pkgs
      run: |
        tox -e deploy

    - name: Test with built wheel
      run: |
        tox -e check
